### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by 15elliotta** [detalhe/vehicle-ai#1]
There is a server issue on the website when submitting a photo.

**Comment by detalhe** [comment]
> There is a server issue on the website when submitting a photo.

Hey, looks like the issue was on the API side, but it's sorted now! Everything should be working as expected.

**Comment by 15elliotta** [comment]
Thank you so much! Sent from my iPhoneOn Dec 13, 2024, at 08:05, Eduardo Monteiro ***@***.***> wrote:﻿

There is a server issue on the website when submitting a photo.

Hey, looks like the issue was on the API side, but it's sorted now! Everything should be working as expected.
